# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hammerstone_pb2 as hammerstone__pb2


class GreeterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/hapi.GreeterService/SayHello',
                request_serializer=hammerstone__pb2.HelloRequest.SerializeToString,
                response_deserializer=hammerstone__pb2.HelloReply.FromString,
                )


class GreeterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=hammerstone__pb2.HelloRequest.FromString,
                    response_serializer=hammerstone__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hapi.GreeterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GreeterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hapi.GreeterService/SayHello',
            hammerstone__pb2.HelloRequest.SerializeToString,
            hammerstone__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.otpAuthenticate = channel.unary_unary(
                '/hapi.ProfileService/otpAuthenticate',
                request_serializer=hammerstone__pb2.OtpAuth.SerializeToString,
                response_deserializer=hammerstone__pb2.OtpAuthResponse.FromString,
                )
        self.addsalesman = channel.unary_unary(
                '/hapi.ProfileService/addsalesman',
                request_serializer=hammerstone__pb2.AddCustomerReq.SerializeToString,
                response_deserializer=hammerstone__pb2.Response.FromString,
                )


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def otpAuthenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addsalesman(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'otpAuthenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.otpAuthenticate,
                    request_deserializer=hammerstone__pb2.OtpAuth.FromString,
                    response_serializer=hammerstone__pb2.OtpAuthResponse.SerializeToString,
            ),
            'addsalesman': grpc.unary_unary_rpc_method_handler(
                    servicer.addsalesman,
                    request_deserializer=hammerstone__pb2.AddCustomerReq.FromString,
                    response_serializer=hammerstone__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hapi.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def otpAuthenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hapi.ProfileService/otpAuthenticate',
            hammerstone__pb2.OtpAuth.SerializeToString,
            hammerstone__pb2.OtpAuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addsalesman(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hapi.ProfileService/addsalesman',
            hammerstone__pb2.AddCustomerReq.SerializeToString,
            hammerstone__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
