# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hammerstone.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hammerstone.proto',
  package='hapi',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11hammerstone.proto\x12\x04hapi\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x07OtpAuth\x12\x0b\n\x03otp\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"j\n\x0fOtpAuthResponse\x12\x1c\n\x04resp\x18\x01 \x01(\x0b\x32\x0e.hapi.Response\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x12\n\nuser_phone\x18\x03 \x01(\t\x12\x12\n\nuser_email\x18\x04 \x01(\t\"7\n\x08Response\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\t\"m\n\x0e\x41\x64\x64\x43ustomerReq\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x12\n\nuser_phone\x18\x02 \x01(\t\x12\x12\n\nuser_email\x18\x03 \x01(\t\x12\x12\n\ncompany_id\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\t2D\n\x0eGreeterService\x12\x32\n\x08SayHello\x12\x12.hapi.HelloRequest\x1a\x10.hapi.HelloReply\"\x00\x32~\n\x0eProfileService\x12\x37\n\x0fotpAuthenticate\x12\r.hapi.OtpAuth\x1a\x15.hapi.OtpAuthResponse\x12\x33\n\x0b\x61\x64\x64salesman\x12\x14.hapi.AddCustomerReq\x1a\x0e.hapi.Responseb\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='hapi.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hapi.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=55,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='hapi.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hapi.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=86,
)


_OTPAUTH = _descriptor.Descriptor(
  name='OtpAuth',
  full_name='hapi.OtpAuth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='otp', full_name='hapi.OtpAuth.otp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='hapi.OtpAuth.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=125,
)


_OTPAUTHRESPONSE = _descriptor.Descriptor(
  name='OtpAuthResponse',
  full_name='hapi.OtpAuthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp', full_name='hapi.OtpAuthResponse.resp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='hapi.OtpAuthResponse.user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_phone', full_name='hapi.OtpAuthResponse.user_phone', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_email', full_name='hapi.OtpAuthResponse.user_email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=233,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='hapi.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='hapi.Response.status_code', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_message', full_name='hapi.Response.status_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=290,
)


_ADDCUSTOMERREQ = _descriptor.Descriptor(
  name='AddCustomerReq',
  full_name='hapi.AddCustomerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='hapi.AddCustomerReq.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_phone', full_name='hapi.AddCustomerReq.user_phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_email', full_name='hapi.AddCustomerReq.user_email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='company_id', full_name='hapi.AddCustomerReq.company_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='role', full_name='hapi.AddCustomerReq.role', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=401,
)

_OTPAUTHRESPONSE.fields_by_name['resp'].message_type = _RESPONSE
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['OtpAuth'] = _OTPAUTH
DESCRIPTOR.message_types_by_name['OtpAuthResponse'] = _OTPAUTHRESPONSE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['AddCustomerReq'] = _ADDCUSTOMERREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'hammerstone_pb2'
  # @@protoc_insertion_point(class_scope:hapi.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'hammerstone_pb2'
  # @@protoc_insertion_point(class_scope:hapi.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

OtpAuth = _reflection.GeneratedProtocolMessageType('OtpAuth', (_message.Message,), {
  'DESCRIPTOR' : _OTPAUTH,
  '__module__' : 'hammerstone_pb2'
  # @@protoc_insertion_point(class_scope:hapi.OtpAuth)
  })
_sym_db.RegisterMessage(OtpAuth)

OtpAuthResponse = _reflection.GeneratedProtocolMessageType('OtpAuthResponse', (_message.Message,), {
  'DESCRIPTOR' : _OTPAUTHRESPONSE,
  '__module__' : 'hammerstone_pb2'
  # @@protoc_insertion_point(class_scope:hapi.OtpAuthResponse)
  })
_sym_db.RegisterMessage(OtpAuthResponse)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'hammerstone_pb2'
  # @@protoc_insertion_point(class_scope:hapi.Response)
  })
_sym_db.RegisterMessage(Response)

AddCustomerReq = _reflection.GeneratedProtocolMessageType('AddCustomerReq', (_message.Message,), {
  'DESCRIPTOR' : _ADDCUSTOMERREQ,
  '__module__' : 'hammerstone_pb2'
  # @@protoc_insertion_point(class_scope:hapi.AddCustomerReq)
  })
_sym_db.RegisterMessage(AddCustomerReq)



_GREETERSERVICE = _descriptor.ServiceDescriptor(
  name='GreeterService',
  full_name='hapi.GreeterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=403,
  serialized_end=471,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='hapi.GreeterService.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETERSERVICE)

DESCRIPTOR.services_by_name['GreeterService'] = _GREETERSERVICE


_PROFILESERVICE = _descriptor.ServiceDescriptor(
  name='ProfileService',
  full_name='hapi.ProfileService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=473,
  serialized_end=599,
  methods=[
  _descriptor.MethodDescriptor(
    name='otpAuthenticate',
    full_name='hapi.ProfileService.otpAuthenticate',
    index=0,
    containing_service=None,
    input_type=_OTPAUTH,
    output_type=_OTPAUTHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='addsalesman',
    full_name='hapi.ProfileService.addsalesman',
    index=1,
    containing_service=None,
    input_type=_ADDCUSTOMERREQ,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROFILESERVICE)

DESCRIPTOR.services_by_name['ProfileService'] = _PROFILESERVICE

# @@protoc_insertion_point(module_scope)
